### ISSUE TITLE
pairs vs ipairs (+speed)

### ISSUE THREAD

**Issue by Titanovsky** [devonium/gproc#1]
Как сделать домашние хинкали по-грузински? Подготовьте продукты. Я взяла готовый говяжий фарш. Петрушку не использовала. Обязательно охладите воду перед началом готовки. Муки может уйти разное количество, будете смотреть по тесту.
ШАГ 2:
Шаг 2.	Муку просейте на рабочую поверхность. Сделайте в центре углубление типа кратера, всыпьте в него соль. Начните понемногу вливать воду в центр, собирая муку от краев к центру.
ШАГ 3:
Шаг 3.	Работайте только вилкой — налили воду, перемешайте — и так до конца, пока не кончится вода.
ШАГ 4:
Шаг 4.	Вся мука должна намокнуть и собраться в комок. Мне пришлось добавить немного воды, потому что тесто оставалось сухим. Имейте в виду, что муки у вас может уйти больше или меньше, чем у меня. Ориентируйтесь на консистенцию теста.
ШАГ 5:
Шаг 5.	Далее начните месить тесто руками. Время от времени разрезайте тесто пополам и выворачивайте его, так как внутри оно более влажное, чем снаружи. Иногда подсыпайте муку, чтобы тесто не прилипало.
ШАГ 6:
Шаг 6.	Месите тесто долго и усердно, оно должно стать крутым, но при этом эластичным.
ШАГ 7:
Шаг 7.	Готовое тесто заверните в пакет и оставьте на два часа "отдыхать". За это время в нем разовьется клейковина, и тесто станет очень эластичным.
ШАГ 8:
Шаг 8.	Пока тесто отлеживается, займитесь фаршем. Если у вас мясо, то прокрутите его через мясорубку вместе с луком. Так как у меня фарш, я просто натерла лук на терке.
ШАГ 9:
Шаг 9.	Зелень хорошо помойте, обсушите. Мелко нарежьте ее.
ШАГ 10:
Шаг 10.	Добавьте в фарш лук, зелень, специи и соль. Хорошо перемешайте.
ШАГ 11:
Шаг 11.	Начните порциями добавлять воду в фарш, хорошо вымешивая после каждой порции. Фарш должен стать жидким. Я добавила воды меньше, около стакана. Готовность фарша можно определить так — воткните в него ложку, она должна начать крениться. Уберите фарш в холодильник на час.
ШАГ 12:
Шаг 12.	Вылежавшееся тесто скатайте в колбаску, затем нарежьте ее на одинаковые куски. Каждый кусок раскатайте в круг толщиной в 2 мм и величиной с ладонь. Старайтесь края сделать тоньше, чем центр.
ШАГ 13:
Шаг 13.	Раскатайте таким образом все куски. Сложите их один на другой, пересыпая мукой. У меня вышло 16 штук, но можно было сделать и все 20, так как хинкали вышли большими.
ШАГ 14:
Шаг 14.	Пришло время лепить хинкали. Для удобства возьмите небольшую пиалку. Накиньте на нее кусок теста. В центр положите столовую ложку фарша. Собирайте края теста складочками в центр.
ШАГ 15:
Шаг 15.	Последнюю складку заверните вокруг других, соединив с первой.
ШАГ 16:
Шаг 16.	Слегка закрутите хвостик против часовой стрелки.
ШАГ 17:
Шаг 17.	Верх хвостика отрежьте ножом.
ШАГ 18:
Шаг 18.	Таким образом сформируйте все хинкали.
ШАГ 19:
Шаг 19.	Чтобы отварить хинкали, вскипятите воду в кастрюле. Посолите ее. Закиньте хинкали. Не варите сразу большое количество, чтобы они не слиплись при варке. Время от времени перемешивайте содержимое кастрюли, чтобы хинкали не прилипли ко дну. Варите хинкали около 14 минут, затем выньте при помощи шумовки на тарелку.

**Comment by devonium** [comment]
ipairs не работает с ассоциативными таблицами ({key = value})
